export const pokemonList = [
    {dex: 1, name: "Bulbasaur"},
    {dex: 2, name: "Ivysaur"},
    {dex: 3, name: "Venusaur"},
    {dex: 4, name: "Charmander"},
    {dex: 5, name: "Charmeleon"},
    {dex: 6, name: "Charizard"},
    {dex: 7, name: "Squirtle"},
    {dex: 8, name: "Wartortle"},
    {dex: 9, name: "Blastoise"},
    {dex: 10, name: "Caterpie"},
    {dex: 11, name: "Metapod"},
    {dex: 12, name: "Butterfree"},
    {dex: 13, name: "Weedle"},
    {dex: 14, name: "Kakuna"},
    {dex: 15, name: "Beedrill"},
    {dex: 16, name: "Pidgey"},
    {dex: 17, name: "Pidgeotto"},
    {dex: 18, name: "Pidgeot"},
    {dex: 19, name: "Rattata"},
    {dex: 20, name: "Raticate"},
    {dex: 21, name: "Spearow"},
    {dex: 22, name: "Fearow"},
    {dex: 23, name: "Ekans"},
    {dex: 24, name: "Arbok"},
    {dex: 25, name: "Pikachu"},
    {dex: 26, name: "Raichu"},
    {dex: 27, name: "Sandshrew"},
    {dex: 28, name: "Sandslash"},
    {dex: 29, name: "Nidoran F"},
    {dex: 30, name: "Nidorina"},
    {dex: 31, name: "Nidoqueen"},
    {dex: 32, name: "Nidoran M"},
    {dex: 33, name: "Nidorino"},
    {dex: 34, name: "Nidoking"},
    {dex: 35, name: "Clefairy"},
    {dex: 36, name: "Clefable"},
    {dex: 37, name: "Vulpix"},
    {dex: 38, name: "Ninetales"},
    {dex: 39, name: "Jigglypuff"},
    {dex: 40, name: "Wigglytuff"},
    {dex: 41, name: "Zubat"},
    {dex: 42, name: "Golbat"},
    {dex: 43, name: "Oddish"},
    {dex: 44, name: "Gloom"},
    {dex: 45, name: "Vileplume"},
    {dex: 46, name: "Paras"},
    {dex: 47, name: "Parasect"},
    {dex: 48, name: "Venonat"},
    {dex: 49, name: "Venomoth"},
    {dex: 50, name: "Diglett"},
    {dex: 51, name: "Dugtrio"},
    {dex: 52, name: "Meowth"},
    {dex: 53, name: "Persian"},
    {dex: 54, name: "Psyduck"},
    {dex: 55, name: "Golduck"},
    {dex: 56, name: "Mankey"},
    {dex: 57, name: "Primeape"},
    {dex: 58, name: "Growlithe"},
    {dex: 59, name: "Arcanine"},
    {dex: 60, name: "Poliwag"},
    {dex: 61, name: "Poliwhirl"},
    {dex: 62, name: "Poliwrath"},
    {dex: 63, name: "Abra"},
    {dex: 64, name: "Kadabra"},
    {dex: 65, name: "Alakazam"},
    {dex: 66, name: "Machop"},
    {dex: 67, name: "Machoke"},
    {dex: 68, name: "Machamp"},
    {dex: 69, name: "Bellsprout"},
    {dex: 70, name: "Weepinbell"},
    {dex: 71, name: "Victreebel"},
    {dex: 72, name: "Tentacool"},
    {dex: 73, name: "Tentacruel"},
    {dex: 74, name: "Geodude"},
    {dex: 75, name: "Graveler"},
    {dex: 76, name: "Golem"},
    {dex: 77, name: "Ponyta"},
    {dex: 78, name: "Rapidash"},
    {dex: 79, name: "Slowpoke"},
    {dex: 80, name: "Slowbro"},
    {dex: 81, name: "Magnemite"},
    {dex: 82, name: "Magneton"},
    {dex: 83, name: "Farfetch'd"},
    {dex: 84, name: "Doduo"},
    {dex: 85, name: "Dodrio"},
    {dex: 86, name: "Seel"},
    {dex: 87, name: "Dewgong"},
    {dex: 88, name: "Grimer"},
    {dex: 89, name: "Muk"},
    {dex: 90, name: "Shellder"},
    {dex: 91, name: "Cloyster"},
    {dex: 92, name: "Gastly"},
    {dex: 93, name: "Haunter"},
    {dex: 94, name: "Gengar"},
    {dex: 95, name: "Onix"},
    {dex: 96, name: "Drowzee"},
    {dex: 97, name: "Hypno"},
    {dex: 98, name: "Krabby"},
    {dex: 99, name: "Kingler"},
    {dex: 100, name: "Voltorb"},
    {dex: 101, name: "Electrode"},
    {dex: 102, name: "Exeggcute"},
    {dex: 103, name: "Exeggutor"},
    {dex: 104, name: "Cubone"},
    {dex: 105, name: "Marowak"},
    {dex: 106, name: "Hitmonlee"},
    {dex: 107, name: "Hitmonchan"},
    {dex: 108, name: "Lickitung"},
    {dex: 109, name: "Koffing"},
    {dex: 110, name: "Weezing"},
    {dex: 111, name: "Rhyhorn"},
    {dex: 112, name: "Rhydon"},
    {dex: 113, name: "Chansey"},
    {dex: 114, name: "Tangela"},
    {dex: 115, name: "Kangaskhan"},
    {dex: 116, name: "Horsea"},
    {dex: 117, name: "Seadra"},
    {dex: 118, name: "Goldeen"},
    {dex: 119, name: "Seaking"},
    {dex: 120, name: "Staryu"},
    {dex: 121, name: "Starmie"},
    {dex: 122, name: "Mr. Mime"},
    {dex: 123, name: "Scyther"},
    {dex: 124, name: "Jynx"},
    {dex: 125, name: "Electabuzz"},
    {dex: 126, name: "Magmar"},
    {dex: 127, name: "Pinsir"},
    {dex: 128, name: "Tauros"},
    {dex: 129, name: "Magikarp"},
    {dex: 130, name: "Gyarados"},
    {dex: 131, name: "Lapras"},
    {dex: 132, name: "Ditto"},
    {dex: 133, name: "Eevee"},
    {dex: 134, name: "Vaporeon"},
    {dex: 135, name: "Jolteon"},
    {dex: 136, name: "Flareon"},
    {dex: 137, name: "Porygon"},
    {dex: 138, name: "Omanyte"},
    {dex: 139, name: "Omastar"},
    {dex: 140, name: "Kabuto"},
    {dex: 141, name: "Kabutops"},
    {dex: 142, name: "Aerodactyl"},
    {dex: 143, name: "Snorlax"},
    {dex: 144, name: "Articuno"},
    {dex: 145, name: "Zapdos"},
    {dex: 146, name: "Moltres"},
    {dex: 147, name: "Dratini"},
    {dex: 148, name: "Dragonair"},
    {dex: 149, name: "Dragonite"},
    {dex: 150, name: "Mewtwo"},
    {dex: 151, name: "Mew"},

    // //GEN 2
    // {dex: 152, name: "Chikorita"},
    // {dex: 153, name: "Bayleef"},
    // {dex: 154, name: "Meganium"},
    // {dex: 155, name: "Cyndaquil"},
    // {dex: 156, name: "Quilava"},
    // {dex: 157, name: "Typhlosion"},
    // {dex: 158, name: "Totodile"},
    // {dex: 159, name: "Croconaw"},
    // {dex: 160, name: "Feraligatr"},
    // {dex: 161, name: "Sentret"},
    // {dex: 162, name: "Furret"},
    // {dex: 163, name: "Hoothoot"},
    // {dex: 164, name: "Noctowl"},
    // {dex: 165, name: "Ledyba"},
    // {dex: 166, name: "Ledian"},
    // {dex: 167, name: "Spinarak"},
    // {dex: 168, name: "Ariados"},
    // {dex: 169, name: "Crobat"},
    // {dex: 170, name: "Chinchou"},
    // {dex: 171, name: "Lanturn"},
    // {dex: 172, name: "Pichu"},
    // {dex: 173, name: "Cleffa"},
    // {dex: 174, name: "Igglybuff"},
    // {dex: 175, name: "Togepi"},
    // {dex: 176, name: "Togetic"},
    // {dex: 177, name: "Natu"},
    // {dex: 178, name: "Xatu"},
    // {dex: 179, name: "Mareep"},
    // {dex: 180, name: "Flaaffy"},
    // {dex: 181, name: "Ampharos"},
    // {dex: 182, name: "Bellossom"},
    // {dex: 183, name: "Marill"},
    // {dex: 184, name: "Azumarill"},
    // {dex: 185, name: "Sudowoodo"},
    // {dex: 186, name: "Politoed"},
    // {dex: 187, name: "Hoppip"},
    // {dex: 188, name: "Skiploom"},
    // {dex: 189, name: "Jumpluff"},
    // {dex: 190, name: "Aipom"},
    // {dex: 191, name: "Sunkern"},
    // {dex: 192, name: "Sunflora"},
    // {dex: 193, name: "Yanma"},
    // {dex: 194, name: "Wooper"},
    // {dex: 195, name: "Quagsire"},
    // {dex: 196, name: "Espeon"},
    // {dex: 197, name: "Umbreon"},
    // {dex: 198, name: "Murkrow"},
    // {dex: 199, name: "Slowking"},
    // {dex: 200, name: "Misdreavus"},
    // {dex: 201, name: "Unown"},
    // {dex: 202, name: "Wobbuffet"},
    // {dex: 203, name: "Girafarig"},
    // {dex: 204, name: "Pineco"},
    // {dex: 205, name: "Forretress"},
    // {dex: 206, name: "Dunsparce"},
    // {dex: 207, name: "Gligar"},
    // {dex: 208, name: "Steelix"},
    // {dex: 209, name: "Snubbull"},
    // {dex: 210, name: "Granbull"},
    // {dex: 211, name: "Qwilfish"},
    // {dex: 212, name: "Scizor"},
    // {dex: 213, name: "Shuckle"},
    // {dex: 214, name: "Heracross"},
    // {dex: 215, name: "Sneasel"},
    // {dex: 216, name: "Teddiursa"},
    // {dex: 217, name: "Ursaring"},
    // {dex: 218, name: "Slugma"},
    // {dex: 219, name: "Magcargo"},
    // {dex: 220, name: "Swinub"},
    // {dex: 221, name: "Piloswine"},
    // {dex: 222, name: "Corsola"},
    // {dex: 223, name: "Remoraid"},
    // {dex: 224, name: "Octillery"},
    // {dex: 225, name: "Delibird"},
    // {dex: 226, name: "Mantine"},
    // {dex: 227, name: "Skarmory"},
    // {dex: 228, name: "Houndour"},
    // {dex: 229, name: "Houndoom"},
    // {dex: 230, name: "Kingdra"},
    // {dex: 231, name: "Phanpy"},
    // {dex: 232, name: "Donphan"},
    // {dex: 233, name: "Porygon2"},
    // {dex: 234, name: "Stantler"},
    // {dex: 235, name: "Smeargle"},
    // {dex: 236, name: "Tyrogue"},
    // {dex: 237, name: "Hitmontop"},
    // {dex: 238, name: "Smoochum"},
    // {dex: 239, name: "Elekid"},
    // {dex: 240, name: "Magby"},
    // {dex: 241, name: "Miltank"},
    // {dex: 242, name: "Blissey"},
    // {dex: 243, name: "Raikou"},
    // {dex: 244, name: "Entei"},
    // {dex: 245, name: "Suicune"},
    // {dex: 246, name: "Larvitar"},
    // {dex: 247, name: "Pupitar"},
    // {dex: 248, name: "Tyranitar"},
    // {dex: 249, name: "Lugia"},
    // {dex: 250, name: "Ho-Oh"},
    // {dex: 251, name: "Celebi"},

    // Gen3 start
];
                                                             

